MVCnews/MVCnews/Controllers/FilesController.cs
using MVCFile.DataSet;
using MVCnews.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCnews.Controllers
{
    public class FilesController : Controller
    {
        private DSFile DB = DSFile.Instance;
        // GET: Files
        public ActionResult Index()
        {
            DataTable dt = new DataTable();
            dt = DB.GetFileData();
            ViewData.Model = dt.AsEnumerable();
            return View();
        }
        [HttpPost]
        public void Store(nFile file)
        {
           
           
        }

        public ActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public ActionResult UploadFiles()
        {
            List<nFile> filelist = new List<nFile>();
            // Checking no of files injected in Request object  
            if (Request.Files.Count > 0)
            {
                try
                {
                    //  Get all files from Request object  
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {
                        nFile obj = new nFile();
                        //string path = AppDomain.CurrentDomain.BaseDirectory + "Uploads/";  
                        //string filename = Path.GetFileName(Request.Files[i].FileName);  

                        HttpPostedFileBase file = files[i];
                        string fname;

                        // Checking for Internet Explorer  
                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                        {
                            string[] testfiles = file.FileName.Split(new char[] { '\\' });
                            fname = testfiles[testfiles.Length - 1];
                        }
                        else
                        {
                           
                              fname = file.FileName;
                        }

                        // Get the complete folder path and store the file inside it.
                        string filename = Path.Combine(Server.MapPath("~/Upload/"), fname);
                        obj.name = fname.Split('.')[0];
                        obj.extension = fname.Split('.')[1];
                        if (System.IO.File.Exists(filename))
                        {
                            int my_counter = 2;
                            string tempfilename = "";
                            //如果有就把相同檔名的檔案改掉,因為可能不只有一個檔名相同而已,所以用while相同都要改,然後數字會遞增去改
                            while (System.IO.File.Exists(filename))
                            {                                
                                tempfilename = fname.Split('.')[0] + my_counter +"."+ fname.Split('.')[1];
                                obj.name = fname.Split('.')[0]+ my_counter;
                                obj.extension = fname.Split('.')[1];                               
                                filename = Path.Combine(Server.MapPath("~/Upload/"), tempfilename);
                                my_counter += 1;
                            }
                            //把修改好的檔名丟給filename
                            fname = tempfilename;                           
                        }
                        obj.url = filename;
                        filelist.Add(obj);
                        file.SaveAs(filename);
                        DB.InsertFile(obj.name, obj.url, obj.extension);
                    }
                    // Returns message that successfully uploaded                      
                    return Json(filelist);
                }
                catch (Exception ex)
                {
                    return Json("Error occurred. Error details: " + ex.Message);
                }
            }
            else
            {
                return Json("No files selected.");
            }
        }
    }
}

MVCnews/MVCnews/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        code {
display:block;
overflow:auto;
font-family:"Courier New";
white-space:pre;
background:#F0F0F0 url(images/CodeBlock.png) repeat-y scroll left top;
border:1px solid #CCC;
margin:5px 15px 0;
padding:5px 5px 5px 20px;
line-height:1.2em;
max-height:280px;
width:90%;
}
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("簡易MVC(Logo)", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("最新消息", "Index", "News")</li>
                    <li>@Html.ActionLink("檔案管理", "Index", "Files")</li>
                    <li>@Html.ActionLink("連絡方式", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
               
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -隨意使用</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>